#!/bin/bash

cp -R ./scripts ./scripts_build

cd ./scripts_build

sudo chmod u+x gaa gacp gc gcb gce gcmsg gcn gm gpo gpom grh gs grlb grlbf grrb ghelp

sudo mv gaa /usr/local/bin 
sudo mv gacp /usr/local/bin 
sudo mv gc /usr/local/bin 
sudo mv gcb /usr/local/bin 
sudo mv gce /usr/local/bin 
sudo mv gcmsg /usr/local/bin 
sudo mv gcn /usr/local/bin 
sudo mv gm /usr/local/bin 
sudo mv gpo /usr/local/bin
sudo mv gpom /usr/local/bin  
sudo mv grh /usr/local/bin 
sudo mv gs /usr/local/bin 
sudo mv grlb /usr/local/bin 
sudo mv grlbf /usr/local/bin
sudo mv grrb /usr/local/bin 
sudo mv ghelp /usr/local/bin   

cd ..

sudo rmdir ./scripts_build


