#!/bin/bash

sudo rm /usr/local/bin/gaa
sudo rm /usr/local/bin/gacp
sudo rm /usr/local/bin/gc
sudo rm /usr/local/bin/gcb
sudo rm /usr/local/bin/gce
sudo rm /usr/local/bin/gcmsg
sudo rm /usr/local/bin/gcn
sudo rm /usr/local/bin/gm
sudo rm /usr/local/bin/gpo
sudo rm /usr/local/bin/gpom
sudo rm /usr/local/bin/grh
sudo rm /usr/local/bin/gs
